import { Roboto } from 'next/font/google';
import '@/styles/globals.css';
import QueryProvider from '@/utils/Providers/QueryProvider';

const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'],
  display: 'swap',
  fallback: ['system-ui', 'sans-serif'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Final Task - Next.js App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html
      lang='en'
      data-theme='light'
      className={roboto.className}
      suppressHydrationWarning
    >
      <QueryProvider>
        <body>{children}</body>
      </QueryProvider>
    </html>
  );
}
